[project]
name = "python-lab4"
version = "0.1.0"
description = "Библиотека с интерактивным доступом"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.2",
    "ruff>=0.14.9",
]
